# Generated by Django 6.0.3 on 2026-05-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sensorreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
